services:
  birdfeeder:
    build:
      context: .
      dockerfile: Dockerfile

    image: birdfeeder-atlas:local
    container_name: birdfeeder

    network_mode: host

    env_file:
      - .env

    volumes:
      - /srv/birdfeeder:/data

    restart: unless-stopped

  birdfeeder-web:
    image: birdfeeder-atlas:local
    container_name: birdfeeder-web

    command:
      - python
      - /app/web.py

    env_file:
      - .env

    volumes:
      - /srv/birdfeeder:/data:ro

    ports:
      - "8080:8080"

    restart: unless-stopped
